### ISSUE TITLE
Pandoc with Pages v3

### ISSUE THREAD

**Issue by vballoli** [sphinx-notes/pages#24]
Just adding it here for a quick reference, easy fix when using https://github.com/sphinx-notes/pages with packages like `nbsphinx`. I hope it helps anyone using this and facing the following error:

```
Please check that pandoc is installed:
http://pandoc.org/installing.html
```

```yaml
name: Deploy Sphinx documentation to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: install_pandoc
      run: sudo apt-get install pandoc
    - id: deployment
      uses: sphinx-notes/pages@v3
```
